import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import LinearContextProvider from "@/contexts/linear-context-provider";
import { LinearTicket } from "@/lib/types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const response = await fetch(
    "http://localhost:3001/api/linear-data"
  );
  if (!response.ok) {
    throw new Error("Failed to fetch Linear data");
  }
  const data: LinearTicket[] = await response.json();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <LinearContextProvider data={data}>{children}</LinearContextProvider>
      </body>
    </html>
  );
}
